#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Sunday 17 April 2022  00:39:38
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.21"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#ff0000"
background = "#80ff80"
transparent = true

[POSITION]
x_pos = 1349
y_pos = -336

[FONT]
size = 66
name = "Twobit"
