#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Sunday 10 April 2022  22:59:30
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.19"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#80ff80"
background = "#000000"
transparent = true

[POSITION]
x_pos = 1354
y_pos = -353
