#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Monday 11 April 2022  21:30:19
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.21"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#ff0000"
background = "#80ff80"
transparent = true

[POSITION]
x_pos = 1333
y_pos = -354

[FONT]
size = 66
name = "Twobit"
