#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Friday 08 April 2022  08:24:22
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.19"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#80ff80"
background = "#000000"
transparent = true

[POSITION]
x_pos = 1355
y_pos = -354
