#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Wednesday 13 April 2022  20:42:46
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.21"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#ff0000"
background = "#80ff80"
transparent = true

[POSITION]
x_pos = 1356
y_pos = -337

[FONT]
size = 66
name = "Twobit"
