#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Saturday 09 July 2022  21:19:47
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.46.beta"
myNAME = "pyKlock"

[COLOUR]
theme = "DarkBlue"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = -899
y_pos = -256

[FONT]
size = 40
name = "Twobit"

[TIME]
type = "GMT Time"
