#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Monday 13 June 2022  22:18:02
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.55"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 365
y_pos = -584

[FONT]
size = 28
name = "Twobit"

[TIME]
type = "Fuzzy Time"
