#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Monday 18 July 2022  20:18:35
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.70"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 376
y_pos = -596

[FONT]
size = 32
name = "Twobit"

[TIME]
type = "Local Time"
