#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Monday 20 June 2022  22:27:05
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.57"
myNAME = "pyKlock"

[COLOUR]
theme = "NeutralBlue"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 449
y_pos = -601

[FONT]
size = 40
name = "KBABCDoodles"

[TIME]
type = "Local Time"
