#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Thursday 19 May 2022  19:56:39
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.44"
myNAME = "pyKlock"

[COLOUR]
theme = "NeutralBlue"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 773
y_pos = -568

[FONT]
size = 24
name = "Twobit"

[TIME]
type = "Time in Words"
