#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Thursday 19 May 2022  23:44:34
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.45"
myNAME = "pyKlock"

[COLOUR]
theme = "NeutralBlue"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = -899
y_pos = -256

[FONT]
size = 24
name = "Twobit"

[TIME]
type = "Time in Words"
