#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Thursday 05 May 2022  22:36:29
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.38"
myNAME = "pyKlock"

[COLOUR]
theme = "DarkBlue1"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = -903
y_pos = -554

[FONT]
size = 76
name = "It Lives In The Swamp BRK"
