#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Saturday 25 June 2022  21:06:42
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.61"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 366
y_pos = -584

[FONT]
size = 40
name = "KBABCDoodles"

[TIME]
type = "Local Time"
