#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Wednesday 29 June 2022  22:52:45
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.63"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 282
y_pos = -306

[FONT]
size = 40
name = "KBABCDoodles"

[TIME]
type = "Local Time"
