#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Sunday 12 June 2022  22:47:47
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.54"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 283
y_pos = -588

[FONT]
size = 40
name = "Twobit"

[TIME]
type = "Local Time"
