#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Sunday 26 June 2022  22:33:21
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.62"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = -886
y_pos = 1

[FONT]
size = 40
name = "KBABCDoodles"

[TIME]
type = "Local Time"
