#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Thursday 28 April 2022  20:42:51
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.36.beta"
myNAME = "pyKlock"

[COLOUR]
theme = "Dark2"

[WINDOW]
width = 294
height = 146
x_pos = 1385
y_pos = 279

[FONT]
size = 76
name = "It Lives In The Swamp BRK"
