#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Sunday 15 May 2022  20:06:32
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.41"
myNAME = "pyKlock"

[COLOUR]
theme = "NeutralBlue"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 272
y_pos = -554

[FONT]
size = 17
name = "Radioland"

[TIME]
type = "Fuzzy Time"
