#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Monday 09 May 2022  20:07:49
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.39.beta"
myNAME = "pyKlock"

[COLOUR]
theme = "NeutralBlue"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 545
y_pos = -352

[FONT]
size = 27
name = "It Lives In The Swamp BRK"

[TIME]
type = "Time in Words"
