#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Wednesday 04 May 2022  22:38:59
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.37.beta"
myNAME = "pyKlock"

[COLOUR]
theme = "DarkBlue1"

[WINDOW]
width = 875
height = 200
x_pos = 593
y_pos = -592

[FONT]
size = 76
name = "It Lives In The Swamp BRK"
