#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Sunday 05 June 2022  21:02:09
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.52"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = -903
y_pos = -268

[FONT]
size = 32
name = "Twobit"

[TIME]
type = "Time in Words"
