#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Friday 13 May 2022  21:09:39
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.40"
myNAME = "pyKlock"

[COLOUR]
theme = "NeutralBlue"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = -902
y_pos = -263

[FONT]
size = 29
name = "Twobit"

[TIME]
type = "Fuzzy Time"
