#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Monday 04 July 2022  20:46:04
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.65"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = 327
y_pos = -612

[FONT]
size = 40
name = "Nancy Blackett semaphore"

[TIME]
type = "Local Time"
