#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Tuesday 21 June 2022  22:45:25
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.59.beta"
myNAME = "pyKlock"

[COLOUR]
theme = "SandyBeach"
foreground = "#ff0000"
background = "#80ff80"
transparent = "false"

[WINDOW]
width = 875
height = 200
x_pos = -899
y_pos = -260

[FONT]
size = 40
name = "KBABCDoodles"

[TIME]
type = "Local Time"
