#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Sunday 24 April 2022  22:31:07
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.31"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#FFFFFF"
background = "#404040"
theme = "NeutralBlue"
transparent = true

[POSITION]
x_pos = 1343
y_pos = -317

[FONT]
size = 66
name = "Twobit"
