#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Monday 18 July 2022  17:06:46
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.32"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#FFFFFF"
background = "#404040"
theme = "NeutralBlue"
transparent = true

[WINDOW]
width = 294
height = 146
x_pos = 1442
y_pos = -305

[FONT]
size = 76
name = "It Lives In The Swamp BRK"
