#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Thursday 21 April 2022  07:02:16
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.24"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#808000"
background = "#f8fe81"
theme = "NeutralBlue"
transparent = "false"

[POSITION]
x_pos = 1511
y_pos = 3

[FONT]
size = 66
name = "Twobit"
