#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Thursday 09 June 2022  22:29:01
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.32"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#FFFFFF"
background = "#404040"
theme = "Dark2"
transparent = true

[WINDOW]
width = 294
height = 146
x_pos = 1416
y_pos = -322

[FONT]
size = 76
name = "It Lives In The Swamp BRK"
