#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Saturday 02 April 2022  18:55:02
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.19"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#ff0000"
background = "#80ff80"
transparent = true

[POSITION]
x_pos = 1389
y_pos = -351
