#   Configure files for pyDigitalKlock.py 
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
#   March 2022    (c) Kevin Scott 

[INFO]
myVERSION = "2022.18"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#ff0000"
background = "#80ff80"

[POSITION]
x_pos = 0
y_pos = 0
