#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Monday 11 April 2022  22:33:18
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.23"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#ff8000"
background = "#80ff80"
transparent = true

[POSITION]
x_pos = 916
y_pos = -354

[FONT]
size = 93
name = "It Lives In The Swamp BRK"
