#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Monday 18 April 2022  21:42:02
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.28"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#ff8000"
background = "#00ff00"
theme = "LightGreen3"
transparent = true

[POSITION]
x_pos = 1186
y_pos = -263

[FONT]
size = 66
name = "Twobit"
