#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Thursday 05 May 2022  22:09:42
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.32"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#d1ecff"
background = "#1a2835"
theme = "NeutralBlue"
transparent = true

[WINDOW]
width = 400
height = 150
x_pos = 241
y_pos = 289

[FONT]
size = 76
name = "Twobit"
