#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Saturday 23 April 2022  21:32:47
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.31"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#FFFFFF"
background = "#404040"
theme = "Dark"
transparent = true

[POSITION]
x_pos = 1338
y_pos = -318

[FONT]
size = 54
name = "Radioland"
