#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Thursday 28 April 2022  19:46:43
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.32"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#d1ecff"
background = "#1a2835"
theme = "DarkBlue"
transparent = true

[WINDOW]
width = 294
height = 146
x_pos = 1385
y_pos = 279

[FONT]
size = 76
name = "It Lives In The Swamp BRK"
