#   Configure file for pyDigitalKlock.py 
#   (c) Kevin Scott   Written Thursday 14 April 2022  19:56:07
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
[INFO]
myVERSION = "2022.24"
myNAME = "pyDigitalKlock"

[COLOUR]
foreground = "#ff8000"
background = "#80ff80"
transparent = true

[POSITION]
x_pos = 927
y_pos = -337

[FONT]
size = 66
name = "Twobit"
